// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtlvmlvqazitemqgkkyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0bHZtbHZxYXppdGVtcWdra3l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTQ0MjksImV4cCI6MjA2NDAzMDQyOX0.mn5YrQW3PGR_9YQrSlRaZJd2MCK-nomSmkIHpsS7IW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);